-- Initial schema for <<PROJECT_TITLE>>.
-- Creates the items table demonstrating the storage layer pattern.
-- IDs are UUIDs (generated by the service layer, not the database).

CREATE TABLE items (
  id TEXT PRIMARY KEY NOT NULL,
  name TEXT NOT NULL CHECK(length(name) <= 200),
  created_at TEXT NOT NULL
);

CREATE INDEX idx_items_created_at ON items (created_at DESC);
